POST http://localhost:3000/medics
Content-Type: application/json

{
  "email": "d1@d.com",
  "password": "pass",
  "image": "yay an image",
  "type": "doctor",
  "shiftStart": 9,
  "shiftEnd": 11
}
###
PUT http://localhost:3000/medics/e8a36fd1-c8e0-4d2a-9048-609a46ef7ebe
Content-Type: application/json

{
  "image": "yay a newer image",
  "shiftEnd": 4,
  "UserId": 123,
  "id": 456
}
###
DELETE http://localhost:3000/medics/e8a36fd1-c8e0-4d2a-9048-609a46ef7ebe
###
GET http://localhost:3000/medics/e8a36fd1-c8e0-4d2a-9048-609a46ef7ebe
###
GET http://localhost:3000/medics