POST http://localhost:3000/medics
Content-Type: application/json

{
  "email": "d1@d.com",
  "password": "pass",
  "image": "yay an image",
  "type": "doctor",
  "shiftStart": 9,
  "shiftEnd": 11,
  "firstName": "Doc",
  "lastName": "McDoctorface"
}
###
GET http://localhost:3000/medics/3317b587-1241-4f9b-a065-bfbdf528c448
###
PATCH http://localhost:3000/medics/eaa79ee5-8e47-4d70-a18f-90fb0440444f
Content-Type: application/json

{
  "image": "yay a newer image",
  "shiftEnd": 4,
  "email": "yay@yay.com",
  "firstName": "trololo",
  "token": "yay look a token!"
}
###
DELETE http://localhost:3000/medics/2a4b4597-f61b-434b-987a-f112e003c7dc
###
GET http://localhost:3000/medics