POST http://localhost:3000/patients
Content-Type: application/json

{
  "email": "patient1@patient.com",
  "password": "pass"
}
###
PUT http://localhost:3000/patients/1

Content-Type: application/json

{

}
###
DELETE http://localhost:3000/patients/1
###
GET http://localhost:3000/patients/1
###
GET http://localhost:3000/patients