POST http://localhost:3000/patients
Content-Type: application/json

{
  "email": "adamlapinski1@gmail.com",
  "password": "pass",
  "firstName": "Pat",
  "lastName": "Mc Patientface",
  "token": "Trololo token",
  "tokenExpires": 1234567890
}
###
GET http://localhost:3000/patients/6623a92c-ec35-4367-8b4c-03b820ceba1e
###
PATCH http://localhost:3000/patients/6623a92c-ec35-4367-8b4c-03b820ceba1e

Content-Type: application/json

{
  "email": "yay an email",
  "firstName": "Pedro",
  "token":"yay a token!",
  "lol":"trolololo"
}
###
DELETE http://localhost:3000/patients/6623a92c-ec35-4367-8b4c-03b820ceba1e
###
GET http://localhost:3000/patients
###
GET http://localhost:3000/patients/appointments