POST http://localhost:3000/users/signup
Content-Type: application/json

{
  "email": "adamlapinski1@gmail.com",
  "password": "passwefasd"
}
###
POST http://localhost:3000/users/signin
Content-Type: application/json

{
  "email": "d1@d.com",
  "password": "pass"
}
###
POST http://localhost:3000/users/signout
###
POST http://localhost:3000/users/forgotpassword
Content-Type: application/json

{
  "email": "adamlapinski1@gmail.com"
}
###
POST http://localhost:3000/users/resetpassword/a8cd513cf1a7eaeb83a40aa19d27816897538fd9
Content-Type: application/json

{
  "password": "yaynewpassword"
}
###
GET http://localhost:3000/users/protected
###
GET http://localhost:3000/users